version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.1.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: google/cloud-sdk:latest

    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          name: annalinze
          command: |
            gsutil ls
      - run:
          name: version
          command: |
            gcloud version
      - run:
          name: init
          command: |
            terraform init
      - run:
          name: plan
          command: |
            terraform plan
