version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.1.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: google/cloud-sdk:latest

    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          name: annalinze
          command: |
            gsutil ls
      - run:
          name: version
          command: |
            gcloud version
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
