name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy
      env:
        GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "rm -rf ${{ secrets.SERVER_DIRECTORY }}/html && git clone -b main --depth 1 https://${{ secrets.PAT }}@github.com/${{ secrets.GIT_USER }}/${{ secrets.GIT_REPO }}.git ${{ secrets.SERVER_DIRECTORY }}/html"
